### ISSUE TITLE
Move util method from ShortToByteFunction.java to separate utils class

### ISSUE THREAD

**Issue by tyran53red** [44TeamSoftware/44team-commons#7]

**Comment by Caps-Looking** [comment]
I'd like help with this, but can you clarify how to run, since there is no main function?

**Comment by Mariyayatskiv** [comment]
Hello! I already did it. Please confirm.

@Caps-Looking Sorry =)

**Comment by tyran53red** [comment]
@Mariyayatskiv Thanks. Done

**Comment by tyran53red** [comment]
@Caps-Looking Sorry, she has already done it. There is not main function to run the project, because it is only commons project. You can compile it and use in another project.
